*--------------------------------------------------
* Fishery Game
* 02_clean_game.do
* START: 2023-05-30
* Authors: Maryia Makhnach, Ivo Steimanis
* Philipps University Marburg
*-------------------------------------------------



*-----------------------
* CLEANING: DROPPPING, RENAMING, REPLACING MISSINGS
*-----------------------
use "$working_ANALYSIS\data\clean\fishery_game_raw.dta", clear
order fishery_game_P11playerunified

/* get list of variables & labels
preserve
describe, replace clear
export excel name vallab varlab using "$raw_data\labels_fishery_game_22_game.xlsx", firstrow(variables) replace
restore
*/

drop participantcode participantlabel participant_is_bot participant_index_in_pages participant_max_page_index participant_current_app_name participant_current_page_name participantvisited participantmturk_worker_id participantmturk_assignment_id
drop participanteffort_history AZ CZ EZ GZ IZ KZ NG QU UI XW ABK AEY AIM AMA APO ATC AWQ BAE
drop participantarea_choice_history AY CY EY GY IY KY NF QT UH XV ABJ AEX AIL ALZ APN ATB AWP BAD
drop participantcost_of_punishing_hi participantpunishment_received_ participantsum_smileys_down_rec participantsum_smileys_down_sen BA BB BC BD DA DB DC DD FA FB FC FD HA HB HC HD JA JB JC JD LA LB LC LD NH NI NJ NK QV QW QX QY UJ UK UL XX UM XY XZ YA ABL ABM ABN ABO AEZ AFA AFB AFC AIN AIO AIP AIQ AMB AMC AMD AME APP APQ APR APS ATE ATD ATF ATG AWR AWS AWT AWU BAF BAG BAH BAI 
drop sessionlabel sessionmturk_HITId sessionmturk_HITGroupId sessioncomment sessionis_demo sessionconfigreal_world_curren sessionconfigname sessionconfigparticipation_fee
drop fishery_game_P11playerrole fishery_game_P12playerrole fishery_game_P13playerrole fishery_game_P14playerrole fishery_game_P15playerrole fishery_game_P16playerrole
drop fishery_game_P11grouptreatmen fishery_game_P12grouptreatmen fishery_game_P13grouptreatmen fishery_game_P14grouptreatmen fishery_game_P15grouptreatmen fishery_game_P16grouptreatmen
drop fishery_game_P12playerunified fishery_game_P13playerunified fishery_game_P14playerunified fishery_game_P15playerunified fishery_game_P16playerunified fishery_game_P21playerunified fishery_game_P22playerunified fishery_game_P23playerunified fishery_game_P24playerunified fishery_game_P25playerunified fishery_game_P26playerunified fishery_game_P31playerunified fishery_game_P32playerunified fishery_game_P33playerunified fishery_game_P34playerunified fishery_game_P35playerunified fishery_game_P36playerunified
drop fishery_game_P12groupid_in_su fishery_game_P13groupid_in_su fishery_game_P14groupid_in_su fishery_game_P15groupid_in_su fishery_game_P16groupid_in_su fishery_game_P21groupid_in_su fishery_game_P22groupid_in_su fishery_game_P23groupid_in_su fishery_game_P24groupid_in_su fishery_game_P25groupid_in_su fishery_game_P26groupid_in_su fishery_game_P31groupid_in_su fishery_game_P32groupid_in_su fishery_game_P33groupid_in_su fishery_game_P34groupid_in_su fishery_game_P35groupid_in_su fishery_game_P36groupid_in_su
drop fishery_game_P11grouptotal_pa fishery_game_P12grouptotal_pa fishery_game_P13grouptotal_pa fishery_game_P14grouptotal_pa fishery_game_P15grouptotal_pa fishery_game_P16grouptotal_pa fishery_game_P21grouptotal_pa fishery_game_P22grouptotal_pa fishery_game_P23grouptotal_pa fishery_game_P24grouptotal_pa fishery_game_P25grouptotal_pa fishery_game_P26grouptotal_pa fishery_game_P31grouptotal_pa fishery_game_P32grouptotal_pa fishery_game_P33grouptotal_pa fishery_game_P34grouptotal_pa fishery_game_P35grouptotal_pa fishery_game_P36grouptotal_pa
drop fishery_game_P12playerid_in_g fishery_game_P13playerid_in_g fishery_game_P14playerid_in_g fishery_game_P15playerid_in_g fishery_game_P16playerid_in_g fishery_game_P21playerid_in_g fishery_game_P22playerid_in_g fishery_game_P23playerid_in_g fishery_game_P24playerid_in_g fishery_game_P25playerid_in_g fishery_game_P26playerid_in_g fishery_game_P31playerid_in_g fishery_game_P32playerid_in_g fishery_game_P33playerid_in_g fishery_game_P34playerid_in_g fishery_game_P36playerid_in_g fishery_game_P35playerid_in_g
drop fishery_game_P16groupdiscussi fishery_game_P26groupdiscussi fishery_game_P36groupdiscussi
drop fishery_game_P21playerrole fishery_game_P22playerrole fishery_game_P23playerrole fishery_game_P24playerrole fishery_game_P25playerrole fishery_game_P26playerrole fishery_game_P31playerrole fishery_game_P32playerrole fishery_game_P33playerrole fishery_game_P34playerrole fishery_game_P35playerrole fishery_game_P36playerrole
drop fishery_game_P21playervote fishery_game_P22playervote fishery_game_P23playervote fishery_game_P24playervote fishery_game_P25playervote fishery_game_P26playervote fishery_game_P31playervote fishery_game_P32playervote fishery_game_P33playervote fishery_game_P34playervote fishery_game_P35playervote fishery_game_P36playervote 
drop RN VB YP ACD AFR AMT AQH ATV AXJ BAX


*** In the 1st round of period 2 and 3 we didn't ask whether they want to change operational or constitutional rules
*P2R1: 
drop fishery_game_P21playeroper_ru PG fishery_game_P21playerconstit PI fishery_game_P21playerrule_ch fishery_game_P21grouprule_vot
*P3R1:
drop fishery_game_P31playeroper_ru AKM fishery_game_P31playerconstit AKO fishery_game_P31playerrule_ch fishery_game_P31grouprule_vot

***Leader election event was possible only in rounds 1 and 4 in periods 2 and 3 depending on the term choice for the leader.
*Variables for characteristics-to-be-revealed weren't used in rounds 2,3,5,6
*area choice characteristics
drop QL TZ ABB AEP ALR APF AWH AZV
*effort choice characteristics
drop QM UA ABC AEQ ALS APG AWI AZW
*punish received characteristics
drop QQ UE ABG AEU ALW APK AWM BAA
*punish sent characteristics
drop QP UD ABF AET ALV APJ AWL AZZ
*smileys received characteristics
drop QO UC ABE AES ALU API AWK AZY
*smileys sent characteristics
drop fishery_game_P22playersmileys fishery_game_P23playersmileys fishery_game_P25playersmileys fishery_game_P26playersmileys fishery_game_P32playersmileys fishery_game_P33playersmileys fishery_game_P35playersmileys fishery_game_P36playersmileys
*reveal nothing
drop fishery_game_P22playerreveal_ fishery_game_P23playerreveal_ fishery_game_P25playerreveal_ fishery_game_P26playerreveal_ fishery_game_P32playerreveal_ fishery_game_P33playerreveal_ fishery_game_P35playerreveal_ fishery_game_P36playerreveal_


/*It was impossible to collect individual choices for monitoring and fines rules because of the real-life voting technique
Only if they had "leader decides" constitutional rule so one person made decisions!
*/

*Intermediate variables (some variables were created for facilitation of calculations):

drop fishery_game_P21grouparea_cho fishery_game_P21groupeffort_c fishery_game_P22grouparea_cho fishery_game_P22groupeffort_c fishery_game_P23grouparea_cho fishery_game_P23groupeffort_c fishery_game_P24grouparea_cho fishery_game_P24groupeffort_c fishery_game_P25grouparea_cho fishery_game_P25groupeffort_c fishery_game_P26grouparea_cho fishery_game_P26groupeffort_c fishery_game_P31grouparea_cho fishery_game_P31groupeffort_c fishery_game_P32grouparea_cho fishery_game_P32groupeffort_c fishery_game_P33grouparea_cho fishery_game_P33groupeffort_c fishery_game_P34grouparea_cho fishery_game_P34groupeffort_c fishery_game_P35grouparea_cho fishery_game_P35groupeffort_c fishery_game_P36grouparea_cho fishery_game_P36groupeffort_c
drop fishery_game_P11groupdiscussi fishery_game_P12groupdiscussi fishery_game_P13groupdiscussi fishery_game_P14groupdiscussi fishery_game_P15groupdiscussi fishery_game_P21groupdiscussi fishery_game_P22groupdiscussi fishery_game_P23groupdiscussi fishery_game_P24groupdiscussi fishery_game_P25groupdiscussi fishery_game_P31groupdiscussi fishery_game_P32groupdiscussi fishery_game_P33groupdiscussi fishery_game_P34groupdiscussi fishery_game_P35groupdiscussi
drop fishery_game_P21groupdecision fishery_game_P22groupdecision fishery_game_P23groupdecision fishery_game_P24groupdecision fishery_game_P25groupdecision fishery_game_P26groupdecision fishery_game_P31groupdecision fishery_game_P32groupdecision fishery_game_P33groupdecision fishery_game_P34groupdecision fishery_game_P35groupdecision fishery_game_P36groupdecision
drop fishery_game_P21groupterm_lim fishery_game_P22groupterm_lim fishery_game_P23groupterm_lim fishery_game_P24groupterm_lim fishery_game_P25groupterm_lim fishery_game_P26groupterm_lim fishery_game_P31groupterm_lim fishery_game_P32groupterm_lim fishery_game_P33groupterm_lim fishery_game_P34groupterm_lim fishery_game_P35groupterm_lim fishery_game_P36groupterm_lim
drop fishery_game_P11groupsomeone_ BO fishery_game_P12groupsomeone_ DO fishery_game_P13groupsomeone_ FO fishery_game_P14groupsomeone_ HO fishery_game_P15groupsomeone_ JO fishery_game_P16groupsomeone_ LO fishery_game_P21groupsomeone_ OK fishery_game_P22groupsomeone_ RY fishery_game_P23groupsomeone_ VM fishery_game_P24groupsomeone_ ZA fishery_game_P25groupsomeone_ ACO fishery_game_P26groupsomeone_ AGC fishery_game_P31groupsomeone_ AJQ fishery_game_P32groupsomeone_ ANE fishery_game_P33groupsomeone_ AQS fishery_game_P34groupsomeone_ AUG fishery_game_P35groupsomeone_ AXU fishery_game_P36groupsomeone_ BBI
drop fishery_game_P21groupoper_rul fishery_game_P22groupoper_rul fishery_game_P23groupoper_rul fishery_game_P24groupoper_rul fishery_game_P25groupoper_rul fishery_game_P26groupoper_rul fishery_game_P31groupoper_rul fishery_game_P32groupoper_rul fishery_game_P33groupoper_rul fishery_game_P34groupoper_rul fishery_game_P35groupoper_rul fishery_game_P36groupoper_rul
drop fishery_game_P21groupconstit_ fishery_game_P22groupconstit_ fishery_game_P23groupconstit_ fishery_game_P24groupconstit_ fishery_game_P25groupconstit_ fishery_game_P26groupconstit_ fishery_game_P31groupconstit_ fishery_game_P32groupconstit_ fishery_game_P33groupconstit_ fishery_game_P34groupconstit_ fishery_game_P35groupconstit_ fishery_game_P36groupconstit_
drop fishery_game_P21grouprule_cha fishery_game_P22grouprule_cha fishery_game_P23grouprule_cha fishery_game_P24grouprule_cha fishery_game_P25grouprule_cha fishery_game_P26grouprule_cha fishery_game_P31grouprule_cha fishery_game_P32grouprule_cha fishery_game_P33grouprule_cha fishery_game_P34grouprule_cha fishery_game_P35grouprule_cha fishery_game_P36grouprule_cha



/*Variables from T4 ONLY!
Group choice whether to change the rules:
fishery_game_P21grouprule_cha fishery_game_P22grouprule_cha fishery_game_P23grouprule_cha fishery_game_P24grouprule_cha fishery_game_P25grouprule_cha fishery_game_P26grouprule_cha fishery_game_P31grouprule_cha fishery_game_P32grouprule_cha fishery_game_P33grouprule_cha fishery_game_P34grouprule_cha fishery_game_P35grouprule_cha fishery_game_P36grouprule_cha

Individual choice whether to change the rules: 
fishery_game_P21playerrule_ch fishery_game_P22playerrule_ch fishery_game_P23playerrule_ch fishery_game_P24playerrule_ch fishery_game_P25playerrule_ch fishery_game_P26playerrule_ch fishery_game_P31playerrule_ch fishery_game_P32playerrule_ch fishery_game_P33playerrule_ch fishery_game_P34playerrule_ch fishery_game_P35playerrule_ch fishery_game_P36playerrule_ch
*/

/*Rule choices pequilarities:
In P2 and P3 in R1 treatments T3, T4 choose constitutional rules with the following variables:

*/

// Renaming & Labeling

rename fishery_game_P11playerunified unified_pl_id
rename participantid_in_session id_in_session
rename village village
rename participanttime_started_utc time_started_utc
rename participantpayoff P3_pl_total_payoff
rename sessioncode sessioncode
rename fishery_game_P11playerid_in_g id_in_gr
rename fishery_game_P11playerpayoff _1pl_payoff
rename fishery_game_P11playerarea_ch _1pl_area_choice
rename fishery_game_P11playereffort_ _1pl_effort_choice
rename fishery_game_P11playerpayoff_ _1pl_payoff_bef_punish
rename fishery_game_P11playerpunish_ _1pl_punish_p1
rename AK _1pl_punish_p2
rename AL _1pl_punish_p3
rename AM _1pl_punish_p4
rename AN _1pl_punish_p5
rename fishery_game_P11playercost_of _1pl_cost_of_punishing
rename fishery_game_P11playerpunishm _1pl_punish_received
rename fishery_game_P11playersmiley_ _1pl_smiley_p1
rename AR _1pl_smiley_p2
rename AS _1pl_smiley_p3
rename AT _1pl_smiley_p4
rename AU _1pl_smiley_p5
rename fishery_game_P11playersum_smi _1pl_sum_smiley_rec
rename AW _1pl_sum_smiley_sent
rename fishery_game_P11playerdiscuss _1pl_discussion_choice
rename fishery_game_P11groupid_in_su treatment
rename fishery_game_P11grouplow_stat _1gr_low_state
rename fishery_game_P11grouppr_low_s _1gr_pr_low_state
rename fishery_game_P11grouppr2_low_ _1gr_pr2_low_state
rename fishery_game_P11groupfisher_e _1gr_fisher_entered
rename fishery_game_P11groupfisher_n _1gr_fisher_not_entered
rename fishery_game_P11groupfisher_h _1gr_fisher_high_effort
rename BP _1gr_fisher_high_A
rename BQ _1gr_fisher_high_B
rename fishery_game_P11groupprev_fis _1gr_prev_fisher_entered
rename fishery_game_P11groupprobabil _1gr_probability
rename fishery_game_P11groupchange _1gr_change
rename fishery_game_P11grouppr_chang _1gr_pr_change
rename fishery_game_P11grouparea_rec _1gr_area_recovered
rename fishery_game_P11grouppr1_area _1gr_pr_area_recovered
rename BX _1gr_area_recov_comb
rename fishery_game_P11grouprandom_n _1gr_random_numb
rename CB _1gr_discussion_voting
rename fishery_game_P11subsessionrou _1subs_round_number
rename fishery_game_P12playerpayoff _2pl_payoff
rename fishery_game_P12playerarea_ch _2pl_area_choice
rename fishery_game_P12playereffort_ _2pl_effort_choice
rename fishery_game_P12playerpayoff_ _2pl_payoff_bef_punish
rename fishery_game_P12playerpunish_ _2pl_punish_p1
rename CK _2pl_punish_p2
rename CL _2pl_punish_p3
rename CM _2pl_punish_p4
rename CN _2pl_punish_p5
rename fishery_game_P12playercost_of _2pl_cost_of_punishing
rename fishery_game_P12playerpunishm _2pl_punish_received
rename fishery_game_P12playersmiley_ _2pl_smiley_p1
rename CR _2pl_smiley_p2
rename CS _2pl_smiley_p3
rename CT _2pl_smiley_p4
rename CU _2pl_smiley_p5
rename fishery_game_P12playersum_smi _2pl_sum_smiley_rec
rename CW _2pl_sum_smiley_sent
rename fishery_game_P12playerdiscuss _2pl_discussion_choice
rename fishery_game_P12grouplow_stat _2gr_low_state
rename fishery_game_P12grouppr_low_s _2gr_pr_low_state
rename fishery_game_P12grouppr2_low_ _2gr_pr2_low_state
rename fishery_game_P12groupfisher_e _2gr_fisher_entered
rename fishery_game_P12groupfisher_n _2gr_fisher_not_entered
rename fishery_game_P12groupfisher_h _2gr_fisher_high_effort
rename DP _2gr_fisher_high_A
rename DQ _2gr_fisher_high_B
rename fishery_game_P12groupprev_fis _2gr_prev_fisher_entered
rename fishery_game_P12groupprobabil _2gr_probability
rename fishery_game_P12groupchange _2gr_change
rename fishery_game_P12grouppr_chang _2gr_pr_change
rename fishery_game_P12grouparea_rec _2gr_area_recovered
rename fishery_game_P12grouppr1_area _2gr_pr_area_recovered
rename DX _2gr_area_recov_comb
rename fishery_game_P12grouprandom_n _2gr_random_numb
rename EB _2gr_discussion_voting
rename fishery_game_P12subsessionrou _2subs_round_number
rename fishery_game_P13playerpayoff _3pl_payoff
rename fishery_game_P13playerarea_ch _3pl_area_choice
rename fishery_game_P13playereffort_ _3pl_effort_choice
rename fishery_game_P13playerpayoff_ _3pl_payoff_bef_punish
rename fishery_game_P13playerpunish_ _3pl_punish_p1
rename EK _3pl_punish_p2
rename EL _3pl_punish_p3
rename EM _3pl_punish_p4
rename EN _3pl_punish_p5
rename fishery_game_P13playercost_of _3pl_cost_of_punishing
rename fishery_game_P13playerpunishm _3pl_punish_received
rename fishery_game_P13playersmiley_ _3pl_smiley_p1
rename ER _3pl_smiley_p2
rename ES _3pl_smiley_p3
rename ET _3pl_smiley_p4
rename EU _3pl_smiley_p5
rename fishery_game_P13playersum_smi _3pl_sum_smiley_rec
rename EW _3pl_sum_smiley_sent
rename fishery_game_P13playerdiscuss _3pl_discussion_choice
rename fishery_game_P13grouplow_stat _3gr_low_state
rename fishery_game_P13grouppr_low_s _3gr_pr_low_state
rename fishery_game_P13grouppr2_low_ _3gr_pr2_low_state
rename fishery_game_P13groupfisher_e _3gr_fisher_entered
rename fishery_game_P13groupfisher_n _3gr_fisher_not_entered
rename fishery_game_P13groupfisher_h _3gr_fisher_high_effort
rename FP _3gr_fisher_high_A
rename FQ _3gr_fisher_high_B
rename fishery_game_P13groupprev_fis _3gr_prev_fisher_entered
rename fishery_game_P13groupprobabil _3gr_probability
rename fishery_game_P13groupchange _3gr_change
rename fishery_game_P13grouppr_chang _3gr_pr_change
rename fishery_game_P13grouparea_rec _3gr_area_recovered
rename fishery_game_P13grouppr1_area _3gr_pr_area_recovered
rename FX _3gr_area_recov_comb
rename fishery_game_P13grouprandom_n _3gr_random_numb
rename GB _3gr_discussion_voting
rename fishery_game_P13subsessionrou _3subs_round_number
rename fishery_game_P14playerpayoff _4pl_payoff
rename fishery_game_P14playerarea_ch _4pl_area_choice
rename fishery_game_P14playereffort_ _4pl_effort_choice
rename fishery_game_P14playerpayoff_ _4pl_payoff_bef_punish
rename fishery_game_P14playerpunish_ _4pl_punish_p1
rename GK _4pl_punish_p2
rename GL _4pl_punish_p3
rename GM _4pl_punish_p4
rename GN _4pl_punish_p5
rename fishery_game_P14playercost_of _4pl_cost_of_punishing
rename fishery_game_P14playerpunishm _4pl_punish_received
rename fishery_game_P14playersmiley_ _4pl_smiley_p1
rename GR _4pl_smiley_p2
rename GS _4pl_smiley_p3
rename GT _4pl_smiley_p4
rename GU _4pl_smiley_p5
rename fishery_game_P14playersum_smi _4pl_sum_smiley_rec
rename GW _4pl_sum_smiley_sent
rename fishery_game_P14playerdiscuss _4pl_discussion_choice
rename fishery_game_P14grouplow_stat _4gr_low_state
rename fishery_game_P14grouppr_low_s _4gr_pr_low_state
rename fishery_game_P14grouppr2_low_ _4gr_pr2_low_state
rename fishery_game_P14groupfisher_e _4gr_fisher_entered
rename fishery_game_P14groupfisher_n _4gr_fisher_not_entered
rename fishery_game_P14groupfisher_h _4gr_fisher_high_effort
rename HP _4gr_fisher_high_A
rename HQ _4gr_fisher_high_B
rename fishery_game_P14groupprev_fis _4gr_prev_fisher_entered
rename fishery_game_P14groupprobabil _4gr_probability
rename fishery_game_P14groupchange _4gr_change
rename fishery_game_P14grouppr_chang _4gr_pr_change
rename fishery_game_P14grouparea_rec _4gr_area_recovered
rename fishery_game_P14grouppr1_area _4gr_pr_area_recovered
rename HX _4gr_area_recov_comb
rename fishery_game_P14grouprandom_n _4gr_random_numb
rename IB _4gr_discussion_voting
rename fishery_game_P14subsessionrou _4subs_round_number
rename fishery_game_P15playerpayoff _5pl_payoff
rename fishery_game_P15playerarea_ch _5pl_area_choice
rename fishery_game_P15playereffort_ _5pl_effort_choice
rename fishery_game_P15playerpayoff_ _5pl_payoff_bef_punish
rename fishery_game_P15playerpunish_ _5pl_punish_p1
rename IK _5pl_punish_p2
rename IL _5pl_punish_p3
rename IM _5pl_punish_p4
rename IN _5pl_punish_p5
rename fishery_game_P15playercost_of _5pl_cost_of_punishing
rename fishery_game_P15playerpunishm _5pl_punish_received
rename fishery_game_P15playersmiley_ _5pl_smiley_p1
rename IR _5pl_smiley_p2
rename IS _5pl_smiley_p3
rename IT _5pl_smiley_p4
rename IU _5pl_smiley_p5
rename fishery_game_P15playersum_smi _5pl_sum_smiley_rec
rename IW _5pl_sum_smiley_sent
rename fishery_game_P15playerdiscuss _5pl_discussion_choice
rename fishery_game_P15grouplow_stat _5gr_low_state
rename fishery_game_P15grouppr_low_s _5gr_pr_low_state
rename fishery_game_P15grouppr2_low_ _5gr_pr2_low_state
rename fishery_game_P15groupfisher_e _5gr_fisher_entered
rename fishery_game_P15groupfisher_n _5gr_fisher_not_entered
rename fishery_game_P15groupfisher_h _5gr_fisher_high_effort
rename JP _5gr_fisher_high_A
rename JQ _5gr_fisher_high_B
rename fishery_game_P15groupprev_fis _5gr_prev_fisher_entered
rename fishery_game_P15groupprobabil _5gr_probability
rename fishery_game_P15groupchange _5gr_change
rename fishery_game_P15grouppr_chang _5gr_pr_change
rename fishery_game_P15grouparea_rec _5gr_area_recovered
rename fishery_game_P15grouppr1_area _5gr_pr_area_recovered
rename JX _5gr_area_recov_comb
rename fishery_game_P15grouprandom_n _5gr_random_numb
rename KB _5gr_discussion_voting
rename fishery_game_P15subsessionrou _5subs_round_number
rename fishery_game_P16playerpayoff _6pl_payoff
rename fishery_game_P16playerarea_ch _6pl_area_choice
rename fishery_game_P16playereffort_ _6pl_effort_choice
rename fishery_game_P16playerpayoff_ _6pl_payoff_bef_punish
rename fishery_game_P16playerpunish_ _6pl_punish_p1
rename KK _6pl_punish_p2
rename KL _6pl_punish_p3
rename KM _6pl_punish_p4
rename KN _6pl_punish_p5
rename fishery_game_P16playercost_of _6pl_cost_of_punishing
rename fishery_game_P16playerpunishm _6pl_punish_received
rename fishery_game_P16playersmiley_ _6pl_smiley_p1
rename KR _6pl_smiley_p2
rename KS _6pl_smiley_p3
rename KT _6pl_smiley_p4
rename KU _6pl_smiley_p5
rename fishery_game_P16playersum_smi _6pl_sum_smiley_rec
rename KW _6pl_sum_smiley_sent
rename fishery_game_P16playerdiscuss _6pl_discussion_choice
rename fishery_game_P16grouplow_stat _6gr_low_state
rename fishery_game_P16grouppr_low_s _6gr_pr_low_state
rename fishery_game_P16grouppr2_low_ _6gr_pr2_low_state
rename fishery_game_P16groupfisher_e _6gr_fisher_entered
rename fishery_game_P16groupfisher_n _6gr_fisher_not_entered
rename fishery_game_P16groupfisher_h _6gr_fisher_high_effort
rename LP _6gr_fisher_high_A
rename LQ _6gr_fisher_high_B
rename fishery_game_P16groupprev_fis _6gr_prev_fisher_entered
rename fishery_game_P16groupprobabil _6gr_probability
rename fishery_game_P16groupchange _6gr_change
rename fishery_game_P16grouppr_chang _6gr_pr_change
rename fishery_game_P16grouparea_rec _6gr_area_recovered
rename fishery_game_P16grouppr1_area _6gr_pr_area_recovered
rename LX _6gr_area_recov_comb
rename fishery_game_P16grouprandom_n _6gr_random_numb
rename MB _6gr_discussion_voting
rename fishery_game_P16subsessionrou _6subs_round_number
rename fishery_game_P21playerpayoff _7pl_payoff
rename fishery_game_P21playerarea_ch _7pl_area_choice
rename fishery_game_P21playereffort_ _7pl_effort_choice
rename fishery_game_P21playerpayoff_ _7pl_payoff_bef_punish
rename fishery_game_P21playerpunish_ _7pl_punish_p1
rename MK _7pl_punish_p2
rename ML _7pl_punish_p3
rename MM _7pl_punish_p4
rename MN _7pl_punish_p5
rename fishery_game_P21playercost_of _7pl_cost_of_punishing
rename fishery_game_P21playerpunishm _7pl_punish_received
rename fishery_game_P21playersmiley_ _7pl_smiley_p1
rename MR _7pl_smiley_p2
rename MS _7pl_smiley_p3
rename MT _7pl_smiley_p4
rename MU _7pl_smiley_p5
rename fishery_game_P21playersum_smi _7pl_sum_smiley_rec
rename MW _7pl_sum_smiley_sent
rename MX _7pl_area_choice_char
rename MY _7pl_effort_choice_char
rename fishery_game_P21playersmileys _7pl_smileys_sent_char
rename NA _7pl_smileys_received_char
rename NB _7pl_punish_sent_char
rename NC _7pl_punish_received_char
rename fishery_game_P21playerreveal_ _7pl_reveal_nothing_char
rename fishery_game_P21playerdecisio _7pl_decision_making_choice
rename fishery_game_P21playerterm_li _7pl_term_limit_choice
rename fishery_game_P21playerarea_ru _7pl_area_rule_choice
rename NO _7pl_effort_rule_choice
rename fishery_game_P21playermonitor _7pl_monitoring_rule_choice
rename fishery_game_P21playerfines_r _7pl_fines_rule_choice
rename fishery_game_P21playerleader_ _7pl_leader_role
rename fishery_game_P21playerdetecti _7pl_detection_area
rename NX _7pl_detection_effort
rename NY _7pl_payoff_bef_monitoring
rename NZ P1_pl_total_payoff
rename fishery_game_P21playerrandom_ _7pl_random_numb_detect
rename fishery_game_P21playerdiscuss _7pl_discussion_choice
rename fishery_game_P21grouplow_stat _7gr_low_state
rename fishery_game_P21grouppr_low_s _7gr_pr_low_state
rename fishery_game_P21grouppr2_low_ _7gr_pr2_low_state
rename fishery_game_P21groupfisher_e _7gr_fisher_entered
rename fishery_game_P21groupfisher_n _7gr_fisher_not_entered
rename fishery_game_P21groupfisher_h _7gr_fisher_high_effort
rename OL _7gr_fisher_high_A
rename OM _7gr_fisher_high_B
rename fishery_game_P21groupprev_fis _7gr_prev_fisher_entered
rename fishery_game_P21groupprobabil _7gr_probability
rename OP _7gr_probability_detect
rename fishery_game_P21groupchange _7gr_change
rename fishery_game_P21grouppr_chang _7gr_pr_change
rename fishery_game_P21grouparea_rec _7gr_area_recovered
rename fishery_game_P21grouppr1_area _7gr_pr_area_recovered
rename OU _7gr_area_recov_comb
rename fishery_game_P21groupleader _7gr_leader
rename fishery_game_P21grouparea_rul _7gr_area_rule
rename fishery_game_P21groupeffort_r _7gr_effort_rule
rename fishery_game_P21groupmonitori _7gr_monitoring_rule
rename fishery_game_P21groupfines_ru _7gr_fines_rule
rename fishery_game_P21groupleader_h _7gr_leader_half_period
rename fishery_game_P21grouprep_cons _7gr_rep_consution
rename fishery_game_P21grouprandom_n _7gr_random_numb
rename PP _7gr_discussion_voting
rename fishery_game_P21subsessionrou _7subs_round_number
rename fishery_game_P22playerpayoff _8pl_payoff
rename fishery_game_P22playerarea_ch _8pl_area_choice
rename fishery_game_P22playereffort_ _8pl_effort_choice
rename fishery_game_P22playerpayoff_ _8pl_payoff_bef_punish
rename fishery_game_P22playerpunish_ _8pl_punish_p1
rename PY _8pl_punish_p2
rename PZ _8pl_punish_p3
rename QA _8pl_punish_p4
rename QB _8pl_punish_p5
rename fishery_game_P22playercost_of _8pl_cost_of_punishing
rename fishery_game_P22playerpunishm _8pl_punish_received
rename fishery_game_P22playersmiley_ _8pl_smiley_p1
rename QF _8pl_smiley_p2
rename QG _8pl_smiley_p3
rename QH _8pl_smiley_p4
rename QI _8pl_smiley_p5
rename fishery_game_P22playersum_smi _8pl_sum_smiley_rec
rename QK _8pl_sum_smiley_sent
rename fishery_game_P22playerdecisio _8pl_decision_making_choice
rename fishery_game_P22playerterm_li _8pl_term_limit_choice
rename fishery_game_P22playerarea_ru _8pl_area_rule_choice
rename RC _8pl_effort_rule_choice
rename fishery_game_P22playermonitor _8pl_monitoring_rule_choice
rename fishery_game_P22playerfines_r _8pl_fines_rule_choice
rename fishery_game_P22playerleader_ _8pl_leader_role
rename fishery_game_P22playeroper_ru _8pl_oper_rule_chg_chc
rename fishery_game_P22playerconstit _8pl_cons_rule_chg_chc
rename fishery_game_P22playerrule_ch _8pl_rule_chg_chc
rename fishery_game_P22playerdetecti _8pl_detection_area
rename RL _8pl_detection_effort
rename RM _8pl_payoff_bef_monitoring
rename fishery_game_P22playerrandom_ _8pl_random_numb_detect
rename fishery_game_P22playerdiscuss _8pl_discussion_choice
rename fishery_game_P22grouplow_stat _8gr_low_state
rename fishery_game_P22grouppr_low_s _8gr_pr_low_state
rename fishery_game_P22grouppr2_low_ _8gr_pr2_low_state
rename fishery_game_P22groupfisher_e _8gr_fisher_entered
rename fishery_game_P22groupfisher_n _8gr_fisher_not_entered
rename fishery_game_P22groupfisher_h _8gr_fisher_high_effort
rename RZ _8gr_fisher_high_A
rename SA _8gr_fisher_high_B
rename fishery_game_P22groupprev_fis _8gr_prev_fisher_entered
rename fishery_game_P22groupprobabil _8gr_probability
rename SD _8gr_probability_detect
rename fishery_game_P22groupchange _8gr_change
rename fishery_game_P22grouppr_chang _8gr_pr_change
rename fishery_game_P22grouparea_rec _8gr_area_recovered
rename fishery_game_P22grouppr1_area _8gr_pr_area_recovered
rename SI _8gr_area_recov_comb
rename fishery_game_P22groupleader _8gr_leader
rename fishery_game_P22grouparea_rul _8gr_area_rule
rename fishery_game_P22groupeffort_r _8gr_effort_rule
rename fishery_game_P22groupmonitori _8gr_monitoring_rule
rename fishery_game_P22groupfines_ru _8gr_fines_rule
rename SU _8gr_oper_rule_voting
rename SW _8gr_cons_rule_voting
rename fishery_game_P22grouprule_vot _8gr_rule_voting
rename fishery_game_P22groupleader_h _8gr_leader_half_period
rename fishery_game_P22grouprep_cons _8gr_rep_consution
rename fishery_game_P22grouprandom_n _8gr_random_numb
rename TD _8gr_discussion_voting
rename fishery_game_P22subsessionrou _8subs_round_number
rename fishery_game_P23playerpayoff _9pl_payoff
rename fishery_game_P23playerarea_ch _9pl_area_choice
rename fishery_game_P23playereffort_ _9pl_effort_choice
rename fishery_game_P23playerpayoff_ _9pl_payoff_bef_punish
rename fishery_game_P23playerpunish_ _9pl_punish_p1
rename TM _9pl_punish_p2
rename TN _9pl_punish_p3
rename TO _9pl_punish_p4
rename TP _9pl_punish_p5
rename fishery_game_P23playercost_of _9pl_cost_of_punishing
rename fishery_game_P23playerpunishm _9pl_punish_received
rename fishery_game_P23playersmiley_ _9pl_smiley_p1
rename TT _9pl_smiley_p2
rename TU _9pl_smiley_p3
rename TV _9pl_smiley_p4
rename TW _9pl_smiley_p5
rename fishery_game_P23playersum_smi _9pl_sum_smiley_rec
rename TY _9pl_sum_smiley_sent
rename fishery_game_P23playerdecisio _9pl_decision_making_choice
rename fishery_game_P23playerterm_li _9pl_term_limit_choice
rename fishery_game_P23playerarea_ru _9pl_area_rule_choice
rename UQ _9pl_effort_rule_choice
rename fishery_game_P23playermonitor _9pl_monitoring_rule_choice
rename fishery_game_P23playerfines_r _9pl_fines_rule_choice
rename fishery_game_P23playerleader_ _9pl_leader_role
rename fishery_game_P23playeroper_ru _9pl_oper_rule_chg_chc
rename fishery_game_P23playerconstit _9pl_cons_rule_chg_chc
rename fishery_game_P23playerrule_ch _9pl_rule_chg_chc
rename fishery_game_P23playerdetecti _9pl_detection_area
rename UZ _9pl_detection_effort
rename VA _9pl_payoff_bef_monitoring
rename fishery_game_P23playerrandom_ _9pl_random_numb_detect
rename fishery_game_P23playerdiscuss _9pl_discussion_choice
rename fishery_game_P23grouplow_stat _9gr_low_state
rename fishery_game_P23grouppr_low_s _9gr_pr_low_state
rename fishery_game_P23grouppr2_low_ _9gr_pr2_low_state
rename fishery_game_P23groupfisher_e _9gr_fisher_entered
rename fishery_game_P23groupfisher_n _9gr_fisher_not_entered
rename fishery_game_P23groupfisher_h _9gr_fisher_high_effort
rename VN _9gr_fisher_high_A
rename VO _9gr_fisher_high_B
rename fishery_game_P23groupprev_fis _9gr_prev_fisher_entered
rename fishery_game_P23groupprobabil _9gr_probability
rename VR _9gr_probability_detect
rename fishery_game_P23groupchange _9gr_change
rename fishery_game_P23grouppr_chang _9gr_pr_change
rename fishery_game_P23grouparea_rec _9gr_area_recovered
rename fishery_game_P23grouppr1_area _9gr_pr_area_recovered
rename VW _9gr_area_recov_comb
rename fishery_game_P23groupleader _9gr_leader
rename fishery_game_P23grouparea_rul _9gr_area_rule
rename fishery_game_P23groupeffort_r _9gr_effort_rule
rename fishery_game_P23groupmonitori _9gr_monitoring_rule
rename fishery_game_P23groupfines_ru _9gr_fines_rule
rename WI _9gr_oper_rule_voting
rename WK _9gr_cons_rule_voting
rename fishery_game_P23grouprule_vot _9gr_rule_voting
rename fishery_game_P23groupleader_h _9gr_leader_half_period
rename fishery_game_P23grouprep_cons _9gr_rep_consution
rename fishery_game_P23grouprandom_n _9gr_random_numb
rename WR _9gr_discussion_voting
rename fishery_game_P23subsessionrou _9subs_round_number
rename fishery_game_P24playerpayoff _10pl_payoff
rename fishery_game_P24playerarea_ch _10pl_area_choice
rename fishery_game_P24playereffort_ _10pl_effort_choice
rename fishery_game_P24playerpayoff_ _10pl_payoff_bef_punish
rename fishery_game_P24playerpunish_ _10pl_punish_p1
rename XA _10pl_punish_p2
rename XB _10pl_punish_p3
rename XC _10pl_punish_p4
rename XD _10pl_punish_p5
rename fishery_game_P24playercost_of _10pl_cost_of_punishing
rename fishery_game_P24playerpunishm _10pl_punish_received
rename fishery_game_P24playersmiley_ _10pl_smiley_p1
rename XH _10pl_smiley_p2
rename XI _10pl_smiley_p3
rename XJ _10pl_smiley_p4
rename XK _10pl_smiley_p5
rename fishery_game_P24playersum_smi _10pl_sum_smiley_rec
rename XM _10pl_sum_smiley_sent
rename XN _10pl_area_choice_char
rename XO _10pl_effort_choice_char
rename fishery_game_P24playersmileys _10pl_smileys_sent_char
rename XQ _10pl_smileys_received_char
rename XR _10pl_punish_sent_char
rename XS _10pl_punish_received_char
rename fishery_game_P24playerreveal_ _10pl_reveal_nothing_char
rename fishery_game_P24playerdecisio _10pl_decision_making_choice
rename fishery_game_P24playerterm_li _10pl_term_limit_choice
rename fishery_game_P24playerarea_ru _10pl_area_rule_choice
rename YE _10pl_effort_rule_choice
rename fishery_game_P24playermonitor _10pl_monitoring_rule_choice
rename fishery_game_P24playerfines_r _10pl_fines_rule_choice
rename fishery_game_P24playerleader_ _10pl_leader_role
rename fishery_game_P24playeroper_ru _10pl_oper_rule_chg_chc
rename fishery_game_P24playerconstit _10pl_cons_rule_chg_chc
rename fishery_game_P24playerrule_ch _10pl_rule_chg_chc
rename fishery_game_P24playerdetecti _10pl_detection_area
rename YN _10pl_detection_effort
rename YO _10pl_payoff_bef_monitoring
rename fishery_game_P24playerrandom_ _10pl_random_numb_detect
rename fishery_game_P24playerdiscuss _10pl_discussion_choice
rename fishery_game_P24grouplow_stat _10gr_low_state
rename fishery_game_P24grouppr_low_s _10gr_pr_low_state
rename fishery_game_P24grouppr2_low_ _10gr_pr2_low_state
rename fishery_game_P24groupfisher_e _10gr_fisher_entered
rename fishery_game_P24groupfisher_n _10gr_fisher_not_entered
rename fishery_game_P24groupfisher_h _10gr_fisher_high_effort
rename ZB _10gr_fisher_high_A
rename ZC _10gr_fisher_high_B
rename fishery_game_P24groupprev_fis _10gr_prev_fisher_entered
rename fishery_game_P24groupprobabil _10gr_probability
rename ZF _10gr_probability_detect
rename fishery_game_P24groupchange _10gr_change
rename fishery_game_P24grouppr_chang _10gr_pr_change
rename fishery_game_P24grouparea_rec _10gr_area_recovered
rename fishery_game_P24grouppr1_area _10gr_pr_area_recovered
rename ZK _10gr_area_recov_comb
rename fishery_game_P24groupleader _10gr_leader
rename fishery_game_P24grouparea_rul _10gr_area_rule
rename fishery_game_P24groupeffort_r _10gr_effort_rule
rename fishery_game_P24groupmonitori _10gr_monitoring_rule
rename fishery_game_P24groupfines_ru _10gr_fines_rule
rename ZW _10gr_oper_rule_voting
rename ZY _10gr_cons_rule_voting
rename fishery_game_P24grouprule_vot _10gr_rule_voting
rename fishery_game_P24groupleader_h _10gr_leader_half_period
rename fishery_game_P24grouprep_cons _10gr_rep_consution
rename fishery_game_P24grouprandom_n _10gr_random_numb
rename AAF _10gr_discussion_voting
rename fishery_game_P24subsessionrou _10subs_round_number
rename fishery_game_P25playerpayoff _11pl_payoff
rename fishery_game_P25playerarea_ch _11pl_area_choice
rename fishery_game_P25playereffort_ _11pl_effort_choice
rename fishery_game_P25playerpayoff_ _11pl_payoff_bef_punish
rename fishery_game_P25playerpunish_ _11pl_punish_p1
rename AAO _11pl_punish_p2
rename AAP _11pl_punish_p3
rename AAQ _11pl_punish_p4
rename AAR _11pl_punish_p5
rename fishery_game_P25playercost_of _11pl_cost_of_punishing
rename fishery_game_P25playerpunishm _11pl_punish_received
rename fishery_game_P25playersmiley_ _11pl_smiley_p1
rename AAV _11pl_smiley_p2
rename AAW _11pl_smiley_p3
rename AAX _11pl_smiley_p4
rename AAY _11pl_smiley_p5
rename fishery_game_P25playersum_smi _11pl_sum_smiley_rec
rename ABA _11pl_sum_smiley_sent
rename fishery_game_P25playerdecisio _11pl_decision_making_choice
rename fishery_game_P25playerterm_li _11pl_term_limit_choice
rename fishery_game_P25playerarea_ru _11pl_area_rule_choice
rename ABS _11pl_effort_rule_choice
rename fishery_game_P25playermonitor _11pl_monitoring_rule_choice
rename fishery_game_P25playerfines_r _11pl_fines_rule_choice
rename fishery_game_P25playerleader_ _11pl_leader_role
rename fishery_game_P25playeroper_ru _11pl_oper_rule_chg_chc
rename fishery_game_P25playerconstit _11pl_cons_rule_chg_chc
rename fishery_game_P25playerrule_ch _11pl_rule_chg_chc
rename fishery_game_P25playerdetecti _11pl_detection_area
rename ACB _11pl_detection_effort
rename ACC _11pl_payoff_bef_monitoring
rename fishery_game_P25playerrandom_ _11pl_random_numb_detect
rename fishery_game_P25playerdiscuss _11pl_discussion_choice
rename fishery_game_P25grouplow_stat _11gr_low_state
rename fishery_game_P25grouppr_low_s _11gr_pr_low_state
rename fishery_game_P25grouppr2_low_ _11gr_pr2_low_state
rename fishery_game_P25groupfisher_e _11gr_fisher_entered
rename fishery_game_P25groupfisher_n _11gr_fisher_not_entered
rename fishery_game_P25groupfisher_h _11gr_fisher_high_effort
rename ACP _11gr_fisher_high_A
rename ACQ _11gr_fisher_high_B
rename fishery_game_P25groupprev_fis _11gr_prev_fisher_entered
rename fishery_game_P25groupprobabil _11gr_probability
rename ACT _11gr_probability_detect
rename fishery_game_P25groupchange _11gr_change
rename fishery_game_P25grouppr_chang _11gr_pr_change
rename fishery_game_P25grouparea_rec _11gr_area_recovered
rename fishery_game_P25grouppr1_area _11gr_pr_area_recovered
rename ACY _11gr_area_recov_comb
rename fishery_game_P25groupleader _11gr_leader
rename fishery_game_P25grouparea_rul _11gr_area_rule
rename fishery_game_P25groupeffort_r _11gr_effort_rule
rename fishery_game_P25groupmonitori _11gr_monitoring_rule
rename fishery_game_P25groupfines_ru _11gr_fines_rule
rename ADK _11gr_oper_rule_voting
rename ADM _11gr_cons_rule_voting
rename fishery_game_P25grouprule_vot _11gr_rule_voting
rename fishery_game_P25groupleader_h _11gr_leader_half_period
rename fishery_game_P25grouprep_cons _11gr_rep_consution
rename fishery_game_P25grouprandom_n _11gr_random_numb
rename ADT _11gr_discussion_voting
rename fishery_game_P25subsessionrou _11subs_round_number
rename fishery_game_P26playerpayoff _12pl_payoff
rename fishery_game_P26playerarea_ch _12pl_area_choice
rename fishery_game_P26playereffort_ _12pl_effort_choice
rename fishery_game_P26playerpayoff_ _12pl_payoff_bef_punish
rename fishery_game_P26playerpunish_ _12pl_punish_p1
rename AEC _12pl_punish_p2
rename AED _12pl_punish_p3
rename AEE _12pl_punish_p4
rename AEF _12pl_punish_p5
rename fishery_game_P26playercost_of _12pl_cost_of_punishing
rename fishery_game_P26playerpunishm _12pl_punish_received
rename fishery_game_P26playersmiley_ _12pl_smiley_p1
rename AEJ _12pl_smiley_p2
rename AEK _12pl_smiley_p3
rename AEL _12pl_smiley_p4
rename AEM _12pl_smiley_p5
rename fishery_game_P26playersum_smi _12pl_sum_smiley_rec
rename AEO _12pl_sum_smiley_sent
rename fishery_game_P26playerdecisio _12pl_decision_making_choice
rename fishery_game_P26playerterm_li _12pl_term_limit_choice
rename fishery_game_P26playerarea_ru _12pl_area_rule_choice
rename AFG _12pl_effort_rule_choice
rename fishery_game_P26playermonitor _12pl_monitoring_rule_choice
rename fishery_game_P26playerfines_r _12pl_fines_rule_choice
rename fishery_game_P26playerleader_ _12pl_leader_role
rename fishery_game_P26playeroper_ru _12pl_oper_rule_chg_chc
rename fishery_game_P26playerconstit _12pl_cons_rule_chg_chc
rename fishery_game_P26playerrule_ch _12pl_rule_chg_chc
rename fishery_game_P26playerdetecti _12pl_detection_area
rename AFP _12pl_detection_effort
rename AFQ _12pl_payoff_bef_monitoring
rename fishery_game_P26playerrandom_ _12pl_random_numb_detect
rename fishery_game_P26playerdiscuss _12pl_discussion_choice
rename fishery_game_P26grouplow_stat _12gr_low_state
rename fishery_game_P26grouppr_low_s _12gr_pr_low_state
rename fishery_game_P26grouppr2_low_ _12gr_pr2_low_state
rename fishery_game_P26groupfisher_e _12gr_fisher_entered
rename fishery_game_P26groupfisher_n _12gr_fisher_not_entered
rename fishery_game_P26groupfisher_h _12gr_fisher_high_effort
rename AGD _12gr_fisher_high_A
rename AGE _12gr_fisher_high_B
rename fishery_game_P26groupprev_fis _12gr_prev_fisher_entered
rename fishery_game_P26groupprobabil _12gr_probability
rename AGH _12gr_probability_detect
rename fishery_game_P26groupchange _12gr_change
rename fishery_game_P26grouppr_chang _12gr_pr_change
rename fishery_game_P26grouparea_rec _12gr_area_recovered
rename fishery_game_P26grouppr1_area _12gr_pr_area_recovered
rename AGM _12gr_area_recov_comb
rename fishery_game_P26groupleader _12gr_leader
rename fishery_game_P26grouparea_rul _12gr_area_rule
rename fishery_game_P26groupeffort_r _12gr_effort_rule
rename fishery_game_P26groupmonitori _12gr_monitoring_rule
rename fishery_game_P26groupfines_ru _12gr_fines_rule
rename AGY _12gr_oper_rule_voting
rename AHA _12gr_cons_rule_voting
rename fishery_game_P26grouprule_vot _12gr_rule_voting
rename fishery_game_P26groupleader_h _12gr_leader_half_period
rename fishery_game_P26grouprep_cons _12gr_rep_consution
rename fishery_game_P26grouprandom_n _12gr_random_numb
rename AHH _12gr_discussion_voting
rename fishery_game_P26subsessionrou _12subs_round_number
rename fishery_game_P31playerpayoff _13pl_payoff
rename fishery_game_P31playerarea_ch _13pl_area_choice
rename fishery_game_P31playereffort_ _13pl_effort_choice
rename fishery_game_P31playerpayoff_ _13pl_payoff_bef_punish
rename fishery_game_P31playerpunish_ _13pl_punish_p1
rename AHQ _13pl_punish_p2
rename AHR _13pl_punish_p3
rename AHS _13pl_punish_p4
rename AHT _13pl_punish_p5
rename fishery_game_P31playercost_of _13pl_cost_of_punishing
rename fishery_game_P31playerpunishm _13pl_punish_received
rename fishery_game_P31playersmiley_ _13pl_smiley_p1
rename AHX _13pl_smiley_p2
rename AHY _13pl_smiley_p3
rename AHZ _13pl_smiley_p4
rename AIA _13pl_smiley_p5
rename fishery_game_P31playersum_smi _13pl_sum_smiley_rec
rename AIC _13pl_sum_smiley_sent
rename AID _13pl_area_choice_char
rename AIE _13pl_effort_choice_char
rename fishery_game_P31playersmileys _13pl_smileys_sent_char
rename AIG _13pl_smileys_received_char
rename AIH _13pl_punish_sent_char
rename AII _13pl_punish_received_char
rename fishery_game_P31playerreveal_ _13pl_reveal_nothing_char
rename fishery_game_P31playerdecisio _13pl_decision_making_choice
rename fishery_game_P31playerterm_li _13pl_term_limit_choice
rename fishery_game_P31playerarea_ru _13pl_area_rule_choice
rename AIU _13pl_effort_rule_choice
rename fishery_game_P31playermonitor _13pl_monitoring_rule_choice
rename fishery_game_P31playerfines_r _13pl_fines_rule_choice
rename fishery_game_P31playerleader_ _13pl_leader_role
rename fishery_game_P31playerdetecti _13pl_detection_area
rename AJD _13pl_detection_effort
rename AJE _13pl_payoff_bef_monitoring
rename AJF P2_pl_total_payoff
rename fishery_game_P31playerrandom_ _13pl_random_numb_detect
rename fishery_game_P31playerdiscuss _13pl_discussion_choice
rename fishery_game_P31grouplow_stat _13gr_low_state
rename fishery_game_P31grouppr_low_s _13gr_pr_low_state
rename fishery_game_P31grouppr2_low_ _13gr_pr2_low_state
rename fishery_game_P31groupfisher_e _13gr_fisher_entered
rename fishery_game_P31groupfisher_n _13gr_fisher_not_entered
rename fishery_game_P31groupfisher_h _13gr_fisher_high_effort
rename AJR _13gr_fisher_high_A
rename AJS _13gr_fisher_high_B
rename fishery_game_P31groupprev_fis _13gr_prev_fisher_entered
rename fishery_game_P31groupprobabil _13gr_probability
rename AJV _13gr_probability_detect
rename fishery_game_P31groupchange _13gr_change
rename fishery_game_P31grouppr_chang _13gr_pr_change
rename fishery_game_P31grouparea_rec _13gr_area_recovered
rename fishery_game_P31grouppr1_area _13gr_pr_area_recovered
rename AKA _13gr_area_recov_comb
rename fishery_game_P31groupleader _13gr_leader
rename fishery_game_P31grouparea_rul _13gr_area_rule
rename fishery_game_P31groupeffort_r _13gr_effort_rule
rename fishery_game_P31groupmonitori _13gr_monitoring_rule
rename fishery_game_P31groupfines_ru _13gr_fines_rule
rename fishery_game_P31groupleader_h _13gr_leader_half_period
rename fishery_game_P31grouprep_cons _13gr_rep_consution
rename fishery_game_P31grouprandom_n _13gr_random_numb
rename AKV _13gr_discussion_voting
rename fishery_game_P31subsessionrou _13subs_round_number
rename fishery_game_P32playerpayoff _14pl_payoff
rename fishery_game_P32playerarea_ch _14pl_area_choice
rename fishery_game_P32playereffort_ _14pl_effort_choice
rename fishery_game_P32playerpayoff_ _14pl_payoff_bef_punish
rename fishery_game_P32playerpunish_ _14pl_punish_p1
rename ALE _14pl_punish_p2
rename ALF _14pl_punish_p3
rename ALG _14pl_punish_p4
rename ALH _14pl_punish_p5
rename fishery_game_P32playercost_of _14pl_cost_of_punishing
rename fishery_game_P32playerpunishm _14pl_punish_received
rename fishery_game_P32playersmiley_ _14pl_smiley_p1
rename ALL _14pl_smiley_p2
rename ALM _14pl_smiley_p3
rename ALN _14pl_smiley_p4
rename ALO _14pl_smiley_p5
rename fishery_game_P32playersum_smi _14pl_sum_smiley_rec
rename ALQ _14pl_sum_smiley_sent
rename fishery_game_P32playerdecisio _14pl_decision_making_choice
rename fishery_game_P32playerterm_li _14pl_term_limit_choice
rename fishery_game_P32playerarea_ru _14pl_area_rule_choice
rename AMI _14pl_effort_rule_choice
rename fishery_game_P32playermonitor _14pl_monitoring_rule_choice
rename fishery_game_P32playerfines_r _14pl_fines_rule_choice
rename fishery_game_P32playerleader_ _14pl_leader_role
rename fishery_game_P32playeroper_ru _14pl_oper_rule_chg_chc
rename fishery_game_P32playerconstit _14pl_cons_rule_chg_chc
rename fishery_game_P32playerrule_ch _14pl_rule_chg_chc
rename fishery_game_P32playerdetecti _14pl_detection_area
rename AMR _14pl_detection_effort
rename AMS _14pl_payoff_bef_monitoring
rename fishery_game_P32playerrandom_ _14pl_random_numb_detect
rename fishery_game_P32playerdiscuss _14pl_discussion_choice
rename fishery_game_P32grouplow_stat _14gr_low_state
rename fishery_game_P32grouppr_low_s _14gr_pr_low_state
rename fishery_game_P32grouppr2_low_ _14gr_pr2_low_state
rename fishery_game_P32groupfisher_e _14gr_fisher_entered
rename fishery_game_P32groupfisher_n _14gr_fisher_not_entered
rename fishery_game_P32groupfisher_h _14gr_fisher_high_effort
rename ANF _14gr_fisher_high_A
rename ANG _14gr_fisher_high_B
rename fishery_game_P32groupprev_fis _14gr_prev_fisher_entered
rename fishery_game_P32groupprobabil _14gr_probability
rename ANJ _14gr_probability_detect
rename fishery_game_P32groupchange _14gr_change
rename fishery_game_P32grouppr_chang _14gr_pr_change
rename fishery_game_P32grouparea_rec _14gr_area_recovered
rename fishery_game_P32grouppr1_area _14gr_pr_area_recovered
rename ANO _14gr_area_recov_comb
rename fishery_game_P32groupleader _14gr_leader
rename fishery_game_P32grouparea_rul _14gr_area_rule
rename fishery_game_P32groupeffort_r _14gr_effort_rule
rename fishery_game_P32groupmonitori _14gr_monitoring_rule
rename fishery_game_P32groupfines_ru _14gr_fines_rule
rename AOA _14gr_oper_rule_voting
rename AOC _14gr_cons_rule_voting
rename fishery_game_P32grouprule_vot _14gr_rule_voting
rename fishery_game_P32groupleader_h _14gr_leader_half_period
rename fishery_game_P32grouprep_cons _14gr_rep_consution
rename fishery_game_P32grouprandom_n _14gr_random_numb
rename AOJ _14gr_discussion_voting
rename fishery_game_P32subsessionrou _14subs_round_number
rename fishery_game_P33playerpayoff _15pl_payoff
rename fishery_game_P33playerarea_ch _15pl_area_choice
rename fishery_game_P33playereffort_ _15pl_effort_choice
rename fishery_game_P33playerpayoff_ _15pl_payoff_bef_punish
rename fishery_game_P33playerpunish_ _15pl_punish_p1
rename AOS _15pl_punish_p2
rename AOT _15pl_punish_p3
rename AOU _15pl_punish_p4
rename AOV _15pl_punish_p5
rename fishery_game_P33playercost_of _15pl_cost_of_punishing
rename fishery_game_P33playerpunishm _15pl_punish_received
rename fishery_game_P33playersmiley_ _15pl_smiley_p1
rename AOZ _15pl_smiley_p2
rename APA _15pl_smiley_p3
rename APB _15pl_smiley_p4
rename APC _15pl_smiley_p5
rename fishery_game_P33playersum_smi _15pl_sum_smiley_rec
rename APE _15pl_sum_smiley_sent
rename fishery_game_P33playerdecisio _15pl_decision_making_choice
rename fishery_game_P33playerterm_li _15pl_term_limit_choice
rename fishery_game_P33playerarea_ru _15pl_area_rule_choice
rename APW _15pl_effort_rule_choice
rename fishery_game_P33playermonitor _15pl_monitoring_rule_choice
rename fishery_game_P33playerfines_r _15pl_fines_rule_choice
rename fishery_game_P33playerleader_ _15pl_leader_role
rename fishery_game_P33playeroper_ru _15pl_oper_rule_chg_chc
rename fishery_game_P33playerconstit _15pl_cons_rule_chg_chc
rename fishery_game_P33playerrule_ch _15pl_rule_chg_chc
rename fishery_game_P33playerdetecti _15pl_detection_area
rename AQF _15pl_detection_effort
rename AQG _15pl_payoff_bef_monitoring
rename fishery_game_P33playerrandom_ _15pl_random_numb_detect
rename fishery_game_P33playerdiscuss _15pl_discussion_choice
rename fishery_game_P33grouplow_stat _15gr_low_state
rename fishery_game_P33grouppr_low_s _15gr_pr_low_state
rename fishery_game_P33grouppr2_low_ _15gr_pr2_low_state
rename fishery_game_P33groupfisher_e _15gr_fisher_entered
rename fishery_game_P33groupfisher_n _15gr_fisher_not_entered
rename fishery_game_P33groupfisher_h _15gr_fisher_high_effort
rename AQT _15gr_fisher_high_A
rename AQU _15gr_fisher_high_B
rename fishery_game_P33groupprev_fis _15gr_prev_fisher_entered
rename fishery_game_P33groupprobabil _15gr_probability
rename AQX _15gr_probability_detect
rename fishery_game_P33groupchange _15gr_change
rename fishery_game_P33grouppr_chang _15gr_pr_change
rename fishery_game_P33grouparea_rec _15gr_area_recovered
rename fishery_game_P33grouppr1_area _15gr_pr_area_recovered
rename ARC _15gr_area_recov_comb
rename fishery_game_P33groupleader _15gr_leader
rename fishery_game_P33grouparea_rul _15gr_area_rule
rename fishery_game_P33groupeffort_r _15gr_effort_rule
rename fishery_game_P33groupmonitori _15gr_monitoring_rule
rename fishery_game_P33groupfines_ru _15gr_fines_rule
rename ARO _15gr_oper_rule_voting
rename ARQ _15gr_cons_rule_voting
rename fishery_game_P33grouprule_vot _15gr_rule_voting
rename fishery_game_P33groupleader_h _15gr_leader_half_period
rename fishery_game_P33grouprep_cons _15gr_rep_consution
rename fishery_game_P33grouprandom_n _15gr_random_numb
rename ARX _15gr_discussion_voting
rename fishery_game_P33subsessionrou _15subs_round_number
rename fishery_game_P34playerpayoff _16pl_payoff
rename fishery_game_P34playerarea_ch _16pl_area_choice
rename fishery_game_P34playereffort_ _16pl_effort_choice
rename fishery_game_P34playerpayoff_ _16pl_payoff_bef_punish
rename fishery_game_P34playerpunish_ _16pl_punish_p1
rename ASG _16pl_punish_p2
rename ASH _16pl_punish_p3
rename ASI _16pl_punish_p4
rename ASJ _16pl_punish_p5
rename fishery_game_P34playercost_of _16pl_cost_of_punishing
rename fishery_game_P34playerpunishm _16pl_punish_received
rename fishery_game_P34playersmiley_ _16pl_smiley_p1
rename ASN _16pl_smiley_p2
rename ASO _16pl_smiley_p3
rename ASP _16pl_smiley_p4
rename ASQ _16pl_smiley_p5
rename fishery_game_P34playersum_smi _16pl_sum_smiley_rec
rename ASS _16pl_sum_smiley_sent
rename AST _16pl_area_choice_char
rename ASU _16pl_effort_choice_char
rename fishery_game_P34playersmileys _16pl_smileys_sent_char
rename ASW _16pl_smileys_received_char
rename ASX _16pl_punish_sent_char
rename ASY _16pl_punish_received_char
rename fishery_game_P34playerreveal_ _16pl_reveal_nothing_char
rename fishery_game_P34playerdecisio _16pl_decision_making_choice
rename fishery_game_P34playerterm_li _16pl_term_limit_choice
rename fishery_game_P34playerarea_ru _16pl_area_rule_choice
rename ATK _16pl_effort_rule_choice
rename fishery_game_P34playermonitor _16pl_monitoring_rule_choice
rename fishery_game_P34playerfines_r _16pl_fines_rule_choice
rename fishery_game_P34playerleader_ _16pl_leader_role
rename fishery_game_P34playeroper_ru _16pl_oper_rule_chg_chc
rename fishery_game_P34playerconstit _16pl_cons_rule_chg_chc
rename fishery_game_P34playerrule_ch _16pl_rule_chg_chc
rename fishery_game_P34playerdetecti _16pl_detection_area
rename ATT _16pl_detection_effort
rename ATU _16pl_payoff_bef_monitoring
rename fishery_game_P34playerrandom_ _16pl_random_numb_detect
rename fishery_game_P34playerdiscuss _16pl_discussion_choice
rename fishery_game_P34grouplow_stat _16gr_low_state
rename fishery_game_P34grouppr_low_s _16gr_pr_low_state
rename fishery_game_P34grouppr2_low_ _16gr_pr2_low_state
rename fishery_game_P34groupfisher_e _16gr_fisher_entered
rename fishery_game_P34groupfisher_n _16gr_fisher_not_entered
rename fishery_game_P34groupfisher_h _16gr_fisher_high_effort
rename AUH _16gr_fisher_high_A
rename AUI _16gr_fisher_high_B
rename fishery_game_P34groupprev_fis _16gr_prev_fisher_entered
rename fishery_game_P34groupprobabil _16gr_probability
rename AUL _16gr_probability_detect
rename fishery_game_P34groupchange _16gr_change
rename fishery_game_P34grouppr_chang _16gr_pr_change
rename fishery_game_P34grouparea_rec _16gr_area_recovered
rename fishery_game_P34grouppr1_area _16gr_pr_area_recovered
rename AUQ _16gr_area_recov_comb
rename fishery_game_P34groupleader _16gr_leader
rename fishery_game_P34grouparea_rul _16gr_area_rule
rename fishery_game_P34groupeffort_r _16gr_effort_rule
rename fishery_game_P34groupmonitori _16gr_monitoring_rule
rename fishery_game_P34groupfines_ru _16gr_fines_rule
rename AVC _16gr_oper_rule_voting
rename AVE _16gr_cons_rule_voting
rename fishery_game_P34grouprule_vot _16gr_rule_voting
rename fishery_game_P34groupleader_h _16gr_leader_half_period
rename fishery_game_P34grouprep_cons _16gr_rep_consution
rename fishery_game_P34grouprandom_n _16gr_random_numb
rename AVL _16gr_discussion_voting
rename fishery_game_P34subsessionrou _16subs_round_number
rename fishery_game_P35playerpayoff _17pl_payoff
rename fishery_game_P35playerarea_ch _17pl_area_choice
rename fishery_game_P35playereffort_ _17pl_effort_choice
rename fishery_game_P35playerpayoff_ _17pl_payoff_bef_punish
rename fishery_game_P35playerpunish_ _17pl_punish_p1
rename AVU _17pl_punish_p2
rename AVV _17pl_punish_p3
rename AVW _17pl_punish_p4
rename AVX _17pl_punish_p5
rename fishery_game_P35playercost_of _17pl_cost_of_punishing
rename fishery_game_P35playerpunishm _17pl_punish_received
rename fishery_game_P35playersmiley_ _17pl_smiley_p1
rename AWB _17pl_smiley_p2
rename AWC _17pl_smiley_p3
rename AWD _17pl_smiley_p4
rename AWE _17pl_smiley_p5
rename fishery_game_P35playersum_smi _17pl_sum_smiley_rec
rename AWG _17pl_sum_smiley_sent
rename fishery_game_P35playerdecisio _17pl_decision_making_choice
rename fishery_game_P35playerterm_li _17pl_term_limit_choice
rename fishery_game_P35playerarea_ru _17pl_area_rule_choice
rename AWY _17pl_effort_rule_choice
rename fishery_game_P35playermonitor _17pl_monitoring_rule_choice
rename fishery_game_P35playerfines_r _17pl_fines_rule_choice
rename fishery_game_P35playerleader_ _17pl_leader_role
rename fishery_game_P35playeroper_ru _17pl_oper_rule_chg_chc
rename fishery_game_P35playerconstit _17pl_cons_rule_chg_chc
rename fishery_game_P35playerrule_ch _17pl_rule_chg_chc
rename fishery_game_P35playerdetecti _17pl_detection_area
rename AXH _17pl_detection_effort
rename AXI _17pl_payoff_bef_monitoring
rename fishery_game_P35playerrandom_ _17pl_random_numb_detect
rename fishery_game_P35playerdiscuss _17pl_discussion_choice
rename fishery_game_P35grouplow_stat _17gr_low_state
rename fishery_game_P35grouppr_low_s _17gr_pr_low_state
rename fishery_game_P35grouppr2_low_ _17gr_pr2_low_state
rename fishery_game_P35groupfisher_e _17gr_fisher_entered
rename fishery_game_P35groupfisher_n _17gr_fisher_not_entered
rename fishery_game_P35groupfisher_h _17gr_fisher_high_effort
rename AXV _17gr_fisher_high_A
rename AXW _17gr_fisher_high_B
rename fishery_game_P35groupprev_fis _17gr_prev_fisher_entered
rename fishery_game_P35groupprobabil _17gr_probability
rename AXZ _17gr_probability_detect
rename fishery_game_P35groupchange _17gr_change
rename fishery_game_P35grouppr_chang _17gr_pr_change
rename fishery_game_P35grouparea_rec _17gr_area_recovered
rename fishery_game_P35grouppr1_area _17gr_pr_area_recovered
rename AYE _17gr_area_recov_comb
rename fishery_game_P35groupleader _17gr_leader
rename fishery_game_P35grouparea_rul _17gr_area_rule
rename fishery_game_P35groupeffort_r _17gr_effort_rule
rename fishery_game_P35groupmonitori _17gr_monitoring_rule
rename fishery_game_P35groupfines_ru _17gr_fines_rule
rename AYQ _17gr_oper_rule_voting
rename AYS _17gr_cons_rule_voting
rename fishery_game_P35grouprule_vot _17gr_rule_voting
rename fishery_game_P35groupleader_h _17gr_leader_half_period
rename fishery_game_P35grouprep_cons _17gr_rep_consution
rename fishery_game_P35grouprandom_n _17gr_random_numb
rename AYZ _17gr_discussion_voting
rename fishery_game_P35subsessionrou _17subs_round_number
rename fishery_game_P36playerpayoff _18pl_payoff
rename fishery_game_P36playerarea_ch _18pl_area_choice
rename fishery_game_P36playereffort_ _18pl_effort_choice
rename fishery_game_P36playerpayoff_ _18pl_payoff_bef_punish
rename fishery_game_P36playerpunish_ _18pl_punish_p1
rename AZI _18pl_punish_p2
rename AZJ _18pl_punish_p3
rename AZK _18pl_punish_p4
rename AZL _18pl_punish_p5
rename fishery_game_P36playercost_of _18pl_cost_of_punishing
rename fishery_game_P36playerpunishm _18pl_punish_received
rename fishery_game_P36playersmiley_ _18pl_smiley_p1
rename AZP _18pl_smiley_p2
rename AZQ _18pl_smiley_p3
rename AZR _18pl_smiley_p4
rename AZS _18pl_smiley_p5
rename fishery_game_P36playersum_smi _18pl_sum_smiley_rec
rename AZU _18pl_sum_smiley_sent
rename fishery_game_P36playerdecisio _18pl_decision_making_choice
rename fishery_game_P36playerterm_li _18pl_term_limit_choice
rename fishery_game_P36playerarea_ru _18pl_area_rule_choice
rename BAM _18pl_effort_rule_choice
rename fishery_game_P36playermonitor _18pl_monitoring_rule_choice
rename fishery_game_P36playerfines_r _18pl_fines_rule_choice
rename fishery_game_P36playerleader_ _18pl_leader_role
rename fishery_game_P36playeroper_ru _18pl_oper_rule_chg_chc
rename fishery_game_P36playerconstit _18pl_cons_rule_chg_chc
rename fishery_game_P36playerrule_ch _18pl_rule_chg_chc
rename fishery_game_P36playerdetecti _18pl_detection_area
rename BAV _18pl_detection_effort
rename BAW _18pl_payoff_bef_monitoring
rename fishery_game_P36playerrandom_ _18pl_random_numb_detect
rename fishery_game_P36playerdiscuss _18pl_discussion_choice
rename fishery_game_P36grouplow_stat _18gr_low_state
rename fishery_game_P36grouppr_low_s _18gr_pr_low_state
rename fishery_game_P36grouppr2_low_ _18gr_pr2_low_state
rename fishery_game_P36groupfisher_e _18gr_fisher_entered
rename fishery_game_P36groupfisher_n _18gr_fisher_not_entered
rename fishery_game_P36groupfisher_h _18gr_fisher_high_effort
rename BBJ _18gr_fisher_high_A
rename BBK _18gr_fisher_high_B
rename fishery_game_P36groupprev_fis _18gr_prev_fisher_entered
rename fishery_game_P36groupprobabil _18gr_probability
rename BBN _18gr_probability_detect
rename fishery_game_P36groupchange _18gr_change
rename fishery_game_P36grouppr_chang _18gr_pr_change
rename fishery_game_P36grouparea_rec _18gr_area_recovered
rename fishery_game_P36grouppr1_area _18gr_pr_area_recovered
rename BBS _18gr_area_recov_comb
rename fishery_game_P36groupleader _18gr_leader
rename fishery_game_P36grouparea_rul _18gr_area_rule
rename fishery_game_P36groupeffort_r _18gr_effort_rule
rename fishery_game_P36groupmonitori _18gr_monitoring_rule
rename fishery_game_P36groupfines_ru _18gr_fines_rule
rename BCE _18gr_oper_rule_voting
rename BCG _18gr_cons_rule_voting
rename fishery_game_P36grouprule_vot _18gr_rule_voting
rename fishery_game_P36groupleader_h _18gr_leader_half_period
rename fishery_game_P36grouprep_cons _18gr_rep_consution
rename fishery_game_P36grouprandom_n _18gr_random_numb
rename BCN _18gr_discussion_voting
rename fishery_game_P36subsessionrou _18subs_round_number


label define groundlabel 0 "Regular" 1 "Spawning"
label values (_1pl_area_choice _2pl_area_choice _3pl_area_choice _4pl_area_choice _5pl_area_choice _6pl_area_choice _7pl_area_choice _7pl_area_choice_char _8pl_area_choice _9pl_area_choice _10pl_area_choice _10pl_area_choice_char _11pl_area_choice _12pl_area_choice _13pl_area_choice _13pl_area_choice_char _14pl_area_choice _15pl_area_choice _16pl_area_choice _16pl_area_choice_char _17pl_area_choice _18pl_area_choice) groundlabel

label define effortlabel 0 "Normal" 1 "High"
label values (_1pl_effort_choice _2pl_effort_choice _3pl_effort_choice _4pl_effort_choice _5pl_effort_choice _6pl_effort_choice _7pl_effort_choice _7pl_effort_choice_char _8pl_effort_choice _9pl_effort_choice _10pl_effort_choice _10pl_effort_choice_char _11pl_effort_choice _12pl_effort_choice _13pl_effort_choice _13pl_effort_choice_char _14pl_effort_choice _15pl_effort_choice _16pl_effort_choice _16pl_effort_choice_char _17pl_effort_choice _18pl_effort_choice) effortlabel

label define constitlabel 0 "Majority vote" 1 "Leader decides"
label values (_7pl_decision_making_choice _8pl_decision_making_choice _9pl_decision_making_choice _10pl_decision_making_choice _11pl_decision_making_choice _12pl_decision_making_choice _13pl_decision_making_choice _14pl_decision_making_choice _15pl_decision_making_choice _16pl_decision_making_choice _17pl_decision_making_choice _18pl_decision_making_choice) constitlabel 

label define leaderelectionlabel 0 "Every 6 rounds" 1 "Every 3 rounds"
label values (_7pl_term_limit_choice _8pl_term_limit_choice _9pl_term_limit_choice _10pl_term_limit_choice _11pl_term_limit_choice _12pl_term_limit_choice _13pl_term_limit_choice _14pl_term_limit_choice _15pl_term_limit_choice _16pl_term_limit_choice _17pl_term_limit_choice _18pl_term_limit_choice) leaderelectionlabel

label define arearulelabel 0 "No restrictions" 1 "Fishing in spawning area is forbidden"
label values (_7pl_area_rule_choice _8pl_area_rule_choice _9pl_area_rule_choice _10pl_area_rule_choice _11pl_area_rule_choice _12pl_area_rule_choice _13pl_area_rule_choice _14pl_area_rule_choice _15pl_area_rule_choice _16pl_area_rule_choice _17pl_area_rule_choice _18pl_area_rule_choice) arearulelabel

label define effortrulelabel 0 "No restrictions" 1 "Fishing with intensive methods is forbidden"
label values (_7pl_effort_rule_choice _8pl_effort_rule_choice _9pl_effort_rule_choice _10pl_effort_rule_choice _11pl_effort_rule_choice _12pl_effort_rule_choice _13pl_effort_rule_choice _14pl_effort_rule_choice _15pl_effort_rule_choice _16pl_effort_rule_choice _17pl_effort_rule_choice _18pl_effort_rule_choice) effortrulelabel

label define monitoringrulelabel 1 "None" 2 "Low level (PHP 2)" 3 "High level (PHP 8)"
label values (_7pl_monitoring_rule_choice _8pl_monitoring_rule_choice _9pl_monitoring_rule_choice _10pl_monitoring_rule_choice _11pl_monitoring_rule_choice _12pl_monitoring_rule_choice _13pl_monitoring_rule_choice _14pl_monitoring_rule_choice _15pl_monitoring_rule_choice _16pl_monitoring_rule_choice _17pl_monitoring_rule_choice _18pl_monitoring_rule_choice) monitoringrulelabel

label define finesrulelabel 1 "None" 2 "Low level (PHP 10)" 3 "High level (PHP 40)"
label values (_7pl_fines_rule_choice _8pl_fines_rule_choice _9pl_fines_rule_choice _10pl_fines_rule_choice _11pl_fines_rule_choice _12pl_fines_rule_choice _13pl_fines_rule_choice _14pl_fines_rule_choice _15pl_fines_rule_choice _16pl_fines_rule_choice _17pl_fines_rule_choice _18pl_fines_rule_choice) finesrulelabel

label define leadertermlabel 0 "6 rounds" 1 "3 rounds"
label values (_7gr_leader_half_period _8gr_leader_half_period _9gr_leader_half_period _10gr_leader_half_period _11gr_leader_half_period _12gr_leader_half_period _13gr_leader_half_period _14gr_leader_half_period _15gr_leader_half_period _16gr_leader_half_period _17gr_leader_half_period _18gr_leader_half_period) leadertermlabel

*Generating new variables:
gen municipality = ""

replace municipality = "Culasi" if village == "Batonan-Sur"
replace municipality = "Libertad" if village == "Bulanao"
replace municipality = "Libertad" if village == "Pajo"
replace municipality = "Libertad" if village == "Pucio"
replace municipality = "Libertad" if village == "San Roque"
replace municipality = "Libertad" if village == "Maramig"
replace municipality = "Tobias Fornier" if village == "Igdalaguit"
replace municipality = "Tobias Fornier" if village == "Paciencia"
replace municipality = "San Lorenzo" if village == "Suclaran"
replace municipality = "Concepcion" if village == "Maliog-liog"
replace municipality = "Concepcion" if village == "Polopina"
replace municipality = "Concepcion" if village == "Taloto-an"
replace municipality = "Dumangas" if village == "Nanding Lopez"
replace municipality = "Dumangas" if village == "Paloc Bigque"
replace municipality = "Guimbal" if village == "Calampitao"
replace municipality = "Guimbal" if village == "Baras"
replace municipality = "San Joaquin" if village == "Bucaya"
replace municipality = "San Joaquin" if village == "Cata-an"
replace municipality = "San Joaquin" if village == "Igcondao"
replace municipality = "San Joaquin" if village == "Sinogbuhan"
replace municipality = "San Joaquin" if village == "Tapikan"
replace municipality = "San Joaquin" if village == "Santa Rita"

gen province = ""

replace province = "Antique" if village == "Batonan-Sur"
replace province = "Antique" if village == "Bulanao"
replace province = "Antique" if village == "Pajo"
replace province = "Antique" if village == "Pucio"
replace province = "Antique" if village == "San Roque"
replace province = "Antique" if village == "Maramig"
replace province = "Antique" if village == "Igdalaguit"
replace province = "Antique" if village == "Paciencia"
replace province = "Guimaras" if village == "Suclaran"
replace province = "Iloilo" if village == "Maliog-liog"
replace province = "Iloilo" if village == "Polopina"
replace province = "Iloilo" if village == "Taloto-an"
replace province = "Iloilo" if village == "Nanding Lopez"
replace province = "Iloilo" if village == "Paloc Bigque"
replace province = "Iloilo" if village == "Calampitao"
replace province = "Iloilo" if village == "Baras"
replace province = "Iloilo" if village == "Bucaya"
replace province = "Iloilo" if village == "Cata-an"
replace province = "Iloilo" if village == "Igcondao"
replace province = "Iloilo" if village == "Sinogbuhan"
replace province = "Iloilo" if village == "Tapikan"
replace province = "Iloilo" if village == "Santa Rita"

***Add results 
gen draw_ball = .

replace draw_ball = 2 if village == "Batonan-Sur" & treatment == 1
replace draw_ball = 3 if village == "Batonan-Sur" & treatment == 2
replace draw_ball = 2 if village == "Batonan-Sur" & treatment == 3
replace draw_ball = 3 if village == "Batonan-Sur" & treatment == 4
replace draw_ball = 2 if village == "Bulanao" & treatment == 1
replace draw_ball = 2 if village == "Bulanao" & treatment == 2
replace draw_ball = 3 if village == "Bulanao" & treatment == 3
replace draw_ball = 1 if village == "Bulanao" & treatment == 4
replace draw_ball = 1 if village == "Pajo" & treatment == 1
replace draw_ball = 2 if village == "Pajo" & treatment == 2
replace draw_ball = 1 if village == "Pajo" & treatment == 3
replace draw_ball = 3 if village == "Pajo" & treatment == 4
replace draw_ball = 3 if village == "Pucio" & treatment == 1
replace draw_ball = 1 if village == "Pucio" & treatment == 2
replace draw_ball = 2 if village == "Pucio" & treatment == 3
replace draw_ball = 2 if village == "Pucio" & treatment == 4
replace draw_ball = 2 if village == "San Roque" & treatment == 1
replace draw_ball = 2 if village == "San Roque" & treatment == 2
replace draw_ball = 1 if village == "San Roque" & treatment == 3
replace draw_ball = 1 if village == "San Roque" & treatment == 4
replace draw_ball = 3 if village == "Maramig" & treatment == 1
replace draw_ball = 2 if village == "Maramig" & treatment == 2
replace draw_ball = 3 if village == "Maramig" & treatment == 3
replace draw_ball = 1 if village == "Maramig" & treatment == 4
replace draw_ball = 1 if village == "Igdalaguit" & treatment == 1
replace draw_ball = 1 if village == "Igdalaguit" & treatment == 2
replace draw_ball = 1 if village == "Igdalaguit" & treatment == 3
replace draw_ball = 1 if village == "Igdalaguit" & treatment == 4
replace draw_ball = 3 if village == "Paciencia" & treatment == 1
replace draw_ball = 3 if village == "Paciencia" & treatment == 2
replace draw_ball = 3 if village == "Paciencia" & treatment == 3
replace draw_ball = 2 if village == "Paciencia" & treatment == 4
replace draw_ball = 2 if village == "Suclaran" & treatment == 1
replace draw_ball = 2 if village == "Suclaran" & treatment == 2
replace draw_ball = 2 if village == "Suclaran" & treatment == 3
replace draw_ball = 2 if village == "Suclaran" & treatment == 4
replace draw_ball = 1 if village == "Maliog-liog" & treatment == 1
replace draw_ball = 3 if village == "Maliog-liog" & treatment == 2
replace draw_ball = 1 if village == "Maliog-liog" & treatment == 3
replace draw_ball = 1 if village == "Maliog-liog" & treatment == 4
replace draw_ball = 2 if village == "Polopina" & treatment == 1
replace draw_ball = 1 if village == "Polopina" & treatment == 2
replace draw_ball = 2 if village == "Polopina" & treatment == 3
replace draw_ball = 1 if village == "Polopina" & treatment == 4
replace draw_ball = 2 if village == "Taloto-an" & treatment == 1
replace draw_ball = 2 if village == "Taloto-an" & treatment == 2
replace draw_ball = 1 if village == "Taloto-an" & treatment == 3
replace draw_ball = 2 if village == "Taloto-an" & treatment == 4
replace draw_ball = 2 if village == "Nanding Lopez" & treatment == 1
replace draw_ball = 3 if village == "Nanding Lopez" & treatment == 2
replace draw_ball = 3 if village == "Nanding Lopez" & treatment == 3
replace draw_ball = 3 if village == "Nanding Lopez" & treatment == 4
replace draw_ball = 1 if village == "Paloc Bigque" & treatment == 1
replace draw_ball = 1 if village == "Paloc Bigque" & treatment == 2
replace draw_ball = 3 if village == "Paloc Bigque" & treatment == 3
replace draw_ball = 2 if village == "Paloc Bigque" & treatment == 4
replace draw_ball = 1 if village == "Calampitao" & treatment == 1
replace draw_ball = 1 if village == "Calampitao" & treatment == 2
replace draw_ball = 2 if village == "Calampitao" & treatment == 3
replace draw_ball = 1 if village == "Calampitao" & treatment == 4
replace draw_ball = 1 if village == "Baras" & treatment == 1
replace draw_ball = 1 if village == "Baras" & treatment == 2
replace draw_ball = 2 if village == "Baras" & treatment == 3
replace draw_ball = 2 if village == "Baras" & treatment == 4
replace draw_ball = 2 if village == "Bucaya" & treatment == 1
replace draw_ball = 1 if village == "Bucaya" & treatment == 2
replace draw_ball = 3 if village == "Bucaya" & treatment == 3
replace draw_ball = 3 if village == "Bucaya" & treatment == 4
replace draw_ball = 3 if village == "Cata-an" & treatment == 1
replace draw_ball = 1 if village == "Cata-an" & treatment == 2
replace draw_ball = 2 if village == "Cata-an" & treatment == 3
replace draw_ball = 3 if village == "Cata-an" & treatment == 4
replace draw_ball = 1 if village == "Igcondao" & treatment == 1
replace draw_ball = 2 if village == "Igcondao" & treatment == 2
replace draw_ball = 3 if village == "Igcondao" & treatment == 3
replace draw_ball = 1 if village == "Igcondao" & treatment == 4
replace draw_ball = 1 if village == "Sinogbuhan" & treatment == 1
replace draw_ball = 1 if village == "Sinogbuhan" & treatment == 2
replace draw_ball = 3 if village == "Sinogbuhan" & treatment == 3
replace draw_ball = 2 if village == "Sinogbuhan" & treatment == 4
replace draw_ball = 3 if village == "Tapikan" & treatment == 1
replace draw_ball = 3 if village == "Tapikan" & treatment == 2
replace draw_ball = 1 if village == "Tapikan" & treatment == 3
replace draw_ball = 2 if village == "Tapikan" & treatment == 4
replace draw_ball = 1 if village == "Santa Rita" & treatment == 1
replace draw_ball = 3 if village == "Santa Rita" & treatment == 2
replace draw_ball = 1 if village == "Santa Rita" & treatment == 3
replace draw_ball = 1 if village == "Santa Rita" & treatment == 4


*Fixing the time and date variable:
format time_started_utc %td
replace time_started_utc = dofc(time_started_utc)
*Date for Maliog-liog is displayed incorrectly 
replace time_started_utc = date("08oct2022","DMY") in 161/180


*Replacing missing values with 0 in the remaining characteristics-to-be-revealed for leader elections
global ElectionRevealCharacteristics _7pl_area_choice_char _7pl_effort_choice_char _7pl_smileys_sent_char _7pl_smileys_received_char _7pl_punish_sent_char _7pl_punish_received_char _7pl_reveal_nothing_char _10pl_area_choice_char _10pl_effort_choice_char _10pl_smileys_sent_char _10pl_smileys_received_char _10pl_punish_sent_char _10pl_punish_received_char _10pl_reveal_nothing_char _13pl_area_choice_char _13pl_effort_choice_char _13pl_smileys_sent_char _13pl_smileys_received_char _13pl_punish_sent_char _13pl_punish_received_char _13pl_reveal_nothing_char _16pl_area_choice_char _16pl_effort_choice_char _16pl_smileys_sent_char _16pl_smileys_received_char _16pl_punish_sent_char _16pl_punish_received_char _16pl_reveal_nothing_char
foreach var in $ElectionRevealCharacteristics {
replace `var' = 0 if missing(`var')
}


*create unique participant identifier for merging with survey data
sort village unified_pl_id
gen unique_id = [_n]


save "$working_ANALYSIS\processed\game_wide.dta", replace




**EOF